// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskApi.DataAccess;

#nullable disable

namespace TaskApi.DataAccess.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20240315015959_tables")]
    partial class tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskAPI.Models.Aurthor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aurthors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Malith Fernandol"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Kevin Aravinda"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Dilina Supun"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AurthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Deu")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AurthorId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AurthorId = 1,
                            Created = new DateTime(2024, 3, 15, 7, 29, 57, 968, DateTimeKind.Local).AddTicks(9539),
                            Description = "Test",
                            Deu = new DateTime(2024, 3, 20, 7, 29, 57, 968, DateTimeKind.Local).AddTicks(9557),
                            Status = 0,
                            Title = "Example 1 - DB"
                        },
                        new
                        {
                            Id = 2,
                            AurthorId = 3,
                            Created = new DateTime(2024, 3, 15, 7, 29, 57, 968, DateTimeKind.Local).AddTicks(9570),
                            Description = "Test",
                            Deu = new DateTime(2024, 3, 20, 7, 29, 57, 968, DateTimeKind.Local).AddTicks(9573),
                            Status = 0,
                            Title = "Example 2 - DB"
                        },
                        new
                        {
                            Id = 3,
                            AurthorId = 2,
                            Created = new DateTime(2024, 3, 15, 7, 29, 57, 968, DateTimeKind.Local).AddTicks(9577),
                            Description = "Test",
                            Deu = new DateTime(2024, 3, 20, 7, 29, 57, 968, DateTimeKind.Local).AddTicks(9579),
                            Status = 0,
                            Title = "Example 3 - DB"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.HasOne("TaskAPI.Models.Aurthor", "Aurthor")
                        .WithMany()
                        .HasForeignKey("AurthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aurthor");
                });
#pragma warning restore 612, 618
        }
    }
}
